language: python

sudo: required

dist: trusty

matrix:
  include:
    - python: "3.4"
    - python: "3.5"
      env:
        - DOCKER_FILE="ubuntu-xenial"
      services: docker
    - python: "3.6"
      env:
        - DOCKER_FILE="ubuntu-bionic"
      services: docker

before_install:
  - if [ -n "$DOCKER_FILE" ]; then
      docker build -t "$DOCKER_FILE" -f ".ci/docker/$DOCKER_FILE" .;
      docker run -itd -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR --env-file .ci/docker/env.list --name my-docker "$DOCKER_FILE";
    fi

install:
  - if [ -n "$DOCKER_FILE" ]; then
      docker exec my-docker /bin/sh -c "cd $TRAVIS_BUILD_DIR && ./.ci/install.sh";
    else
      '.ci/install.sh';
    fi

script:
  - if [ -n "$DOCKER_FILE" ]; then
      docker exec my-docker /bin/sh -c "cd $TRAVIS_BUILD_DIR && ./.ci/script.sh";
    else
      '.ci/script.sh';
    fi
